spring.datasource.url=jdbc:postgresql://ep-solitary-leaf-as927tww-pooler.c-4.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_v3xk1wLTOAbV
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
aws.region=eu-west-3
aws.sqs.queue.url=https://sqs.eu-west-3.amazonaws.com/000000000000/dummy-queue
aws.eventBridge.bus=dummy-bus
aws.s3.bucket=dummy-bucket
aws.ses.source=noreply@poja.io



